services:
  - type: web
    name: ecommerce-project
    runtime: node
    rootDir: lab-final-b
    plan: free
    autoDeploy: true
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
